# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1
description: |
  Deploy a Kubernetes Cluster from CircleCI using the Rafay Systems Platform. Rafay’s turnkey SaaS platform automates the highly complex deployment and operational workflows that DevOps and SRE teams implement to operate Kubernetes clusters and Kubernetes-resident apps across clusters in cloud and data center environments. The platform accelerates organizations’ respective application modernization journeys by abstracting away the complexities of Kubernetes and other open-source container management tools. Learn more: https://rafay.co/enterprise-integrations/circleci
orbs: 
  rafay: rafaysystems/rafay@1.0.7
display:
  source_url: https://github.com/RafaySystems/circleci-orb
  home_url: https://rafay.co

commands:
  init:

    steps:
      - run:
         command: |
           wget -O ${HOME}/rctl-linux-amd64.tar.bz2 https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2
           tar -C ${HOME} -xf ${HOME}/rctl-linux-amd64.tar.bz2
           chmod 0755 ${HOME}/rctl
           mkdir -p ${HOME}/.rafay/cli
  publish_workload:
    description: test8
    parameters: pod-only.yaml
      workload: kvxdqvm
        description: test8
        type: string
    steps:
      - run:
         ${HOME}/rctl publish workload pod-only.yaml

    

executors:
  default:
    description: |
      This is a machine executor.
    machine: true
       workflows:
        version: 2
        build-and-publish-workload-to-rafay:
          jobs:
            - build-job
            - Publish-Workload:
                requires:
                  - build-job
            - Test-Workload:
                requires:
                  - build-job
                  - Publish-Workload
            - Delete-Workload:
                requires:
                  - build-job
                  - Publish-Workload
                  - Test-Workload

